Support for OSX in kmsn / kmsp. No longer using 'readlink' (we don't actually care whether the directory containing the script is a symlink or not). Readability cleanup in the 'usage' line to make it more GNU/BSD style. Removed dependency on proc for testing if a PID exists, instead using "kill -0" in kmsp.

diff --git a/kmsp b/kmsp
--- a/kmsp
+++ b/kmsp
@@ -1,11 +1,15 @@
 #!/bin/bash
-. "$(dirname $(readlink -f $0))/kms_functions"
+. "$(dirname "${BASH_SOURCE[0]}")/kms_functions"
 
-[ -z "$1" ] && { echo -e "Kill processes softly by pid number\nUsage:\n$0 first_pid_to_kill [second_pid_to_kill] <...>\n"; exit 1; }
+[ -z "$1" ] && { 
+    echo -e "Kill processes softly by pid number"
+    echo -e "usage: $(basename "${0}") first_pid_to_kill [second_pid_to_kill] <...>\n"
+    exit 1
+}
 
 while (( "$#" )); do
     [[ ! "$1" =~ ^[0-9]+$ ]] && { echo "Invalid process pid ${1}, skipping"; shift; continue; }
-    [ ! -e "/proc/$1" ] && { echo "PID ${1} not found among running processes, skipping"; shift; continue; }
+    kill -0 $1 2>/dev/null || { echo "PID ${1} not found among running processes, skipping"; shift; continue; }
     killmesoftly $1
     shift
 done
